ARG BASE_IMAGE
FROM ${BASE_IMAGE} AS builder
FROM debian:13 AS debian

FROM gcr.io/distroless/cc-debian13:nonroot
COPY --from=builder /home/rust/src/target/release/revolt-delta ./
COPY --from=builder /home/rust/src/target/release/revolt-bonfire ./
COPY --from=debian /usr/bin/uname /usr/bin/uname
EXPOSE 14702 14703
USER nonroot
