import { plural } from "nucleo/lib/plural";

/**
 * Textos da administração básica (PRD 4.7): criar o servidor, salas e canais,
 * convites, cargos, moderação e sair. Sem texto de engenharia: quem tenta banir
 * alguém acima de si lê "você não pode moderar esta pessoa", não o código do
 * erro. Servidor e sala são palavras do produto; canal é o texto.
 */
export const admin = {
  servidor: "Servidor",
  canais: "Canais",
  convites: "Convites",
  cargos: "Cargos",
  moderacao: "Moderação",
  banir: "Banir",
  expulsar: "Expulsar",
  criarConvite: "Criar convite",
  confirmarApagar: (nome: string) => `Apagar ${nome}? Isso não pode ser desfeito.`,

  /** Cabeçalho do servidor, na coluna de salas. */
  menu: {
    abrir: "Opções do servidor",
    convidar: "Convidar pessoas",
    configuracoes: "Configurações do servidor",
    sair: "Sair do servidor",
    apagar: "Apagar o servidor",
  },

  /** A navegação das configurações do servidor. */
  navegacao: {
    rotulo: "Seções do servidor",
    grupoServidor: "Servidor",
    grupoPessoas: "Pessoas",
    grupoModeracao: "Moderação",
    visaoGeral: "Visão geral",
    salasECanais: "Salas e canais",
    convites: "Convites",
    cargos: "Cargos",
    membros: "Membros",
    banimentos: "Banimentos",
  },
  subtitulos: {
    visaoGeral: "Nome, ícone e descrição do servidor.",
    salasECanais: "Use as setas para mudar a ordem dentro de cada categoria.",
    convites: "Quem tiver o link entra no servidor. Revogue para o link parar de funcionar.",
    cargos: "Quem pode fazer o quê no servidor.",
    membros: "Quem está no servidor e o que cada pessoa pode fazer.",
    banimentos: "Quem foi banido e não pode voltar.",
  },

  /** Criar um servidor ou entrar por convite. */
  criarServidor: {
    titulo: "Adicionar um servidor",
    descricao: "Crie o seu ou entre num que alguém te convidou.",
    abas: "O que você quer fazer",
    abaCriar: "Criar um servidor",
    abaEntrar: "Entrar com um convite",
    nome: "Nome do servidor",
    nomePlaceholder: "Jogatina da turma",
    nomeObrigatorio: "Dê um nome ao servidor.",
    salaInicial: "Geral",
    jaVem: "Já vem com uma sala de voz e um canal de texto, para você começar a conversar.",
    imagem: "Aparece na coluna de servidores.",
    criar: "Criar servidor",
    criando: "Criando…",
    falhou: "Não deu para criar o servidor. Tente de novo.",
    convite: "Link ou código do convite",
    convitePlaceholder: "Cole o link que alguém te mandou",
    conviteAjuda: "Cole o link para ver o servidor antes de entrar.",
    buscando: "Procurando o convite…",
    conviteValido: "Convite válido",
    membros: (n: number) => plural(n, "pessoa", "pessoas"),
    jaSouMembro: "Você já está neste servidor.",
    entrar: "Entrar no servidor",
    abrir: "Abrir o servidor",
    entrando: "Entrando…",
    pedidoEnviado: "Pedido enviado. Quem cuida do servidor vai avaliar a sua entrada.",
    banido: "Você foi banido deste servidor e não pode voltar.",
    entrouEm: (nome: string) => `Você entrou em ${nome}.`,
    criouEm: (nome: string) => `${nome} foi criado.`,
  },

  /** Sair, ou apagar, para o dono. */
  sair: {
    tituloMembro: (nome: string) => `Sair de ${nome}?`,
    textoMembro: "Você pode voltar com um novo convite.",
    confirmarMembro: "Sair",
    tituloDono: (nome: string) => `Apagar ${nome}?`,
    textoDono: "Você é o dono. Se sair, o servidor é apagado para todo mundo: salas, canais e mensagens somem e não dá para recuperar.",
    manter: "Quer manter o servidor?",
    manterTexto: "Passe a propriedade para outra pessoa e depois saia sem apagar nada.",
    transferir: "Transferir a propriedade",
    paraConfirmar: "Para confirmar, digite o nome do servidor",
    confirmarDono: "Apagar servidor",
    saindo: "Saindo…",
    apagando: "Apagando…",
    saiu: (nome: string) => `Você saiu de ${nome}.`,
    apagou: (nome: string) => `${nome} foi apagado.`,
  },
  transferir: {
    titulo: "Transferir a propriedade",
    descricao: "A pessoa escolhida passa a ser a dona. Só ela pode devolver.",
    para: "Nova dona ou novo dono",
    escolher: "Escolha uma pessoa",
    semPessoas: "Não há mais ninguém no servidor para receber a propriedade.",
    paraConfirmar: "Para confirmar, digite o nome do servidor",
    confirmar: "Transferir",
    transferindo: "Transferindo…",
    feito: (nome: string) => `${nome} agora é quem manda no servidor.`,
  },

  /** Visão geral do servidor. */
  visaoGeral: {
    icone: "Ícone",
    trocarIcone: "Trocar ícone",
    removerIcone: "Remover ícone",
    enviando: "Enviando…",
    semMidia: "Este servidor não aceita imagens no momento.",
    nome: "Nome do servidor",
    nomeObrigatorio: "O servidor precisa de um nome.",
    descricao: "Descrição",
    descricaoPlaceholder: "Conte o que o grupo faz",
    salvo: "Servidor salvo.",
    zonaDeRisco: "Sair do servidor",
    zonaDeRiscoDono: "Você é o dono. Passe a propriedade antes de sair, ou apague o servidor.",
    zonaDeRiscoMembro: "Você pode voltar com um novo convite.",
  },

  /** Salas e canais. */
  canaisPagina: {
    criar: "Criar sala ou canal",
    criarCategoria: "Criar categoria",
    vazio: "Este servidor ainda não tem salas nem canais.",
    vazioAcao: "Crie a primeira sala de voz para o grupo se encontrar.",
    categoria: "Categoria",
    categoriaVazia: "Nenhum canal nesta categoria.",
    semCategoria: "Sem categoria",
    sala: "Sala de voz",
    canal: "Canal de texto",
    tipo: "Tipo",
    nome: "Nome",
    nomeObrigatorio: "Dê um nome.",
    criarTitulo: "Criar sala ou canal",
    editarTitulo: "Editar sala ou canal",
    criarConfirmar: "Criar",
    salvarConfirmar: "Salvar",
    assunto: "Assunto",
    assuntoPlaceholder: "Sobre o que se fala aqui",
    editar: (nome: string) => `Editar ${nome}`,
    duplicar: (nome: string) => `Duplicar ${nome}`,
    apagar: (nome: string) => `Apagar ${nome}`,
    subir: (nome: string) => `Subir ${nome}`,
    descer: (nome: string) => `Descer ${nome}`,
    apagarTitulo: (nome: string) => `Apagar ${nome}?`,
    apagarSala: "A sala some para todo mundo e quem está nela é desconectado. Não dá para desfazer.",
    apagarCanal: "O canal e todas as mensagens dele somem para todo mundo. Não dá para desfazer.",
    apagarConfirmar: "Apagar",
    nomeDaCategoria: "Nome da categoria",
    renomearCategoria: (nome: string) => `Renomear a categoria ${nome}`,
    apagarCategoria: (nome: string) => `Apagar a categoria ${nome}`,
    apagarCategoriaTitulo: (nome: string) => `Apagar a categoria ${nome}?`,
    apagarCategoriaTexto: "Os canais dela não são apagados: ficam sem categoria.",
    criada: "Criado.",
    duplicada: "Duplicado.",
    apagada: "Apagado.",
    falhou: "Não deu para concluir. Tente de novo.",
  },

  /** Convites. */
  convitesPagina: {
    criar: "Criar convite",
    codigo: "Código",
    criadoPor: "Criado por",
    canal: "Canal",
    revogar: "Revogar",
    revogarConvite: (codigo: string) => `Revogar o convite ${codigo}`,
    revogarTitulo: (codigo: string) => `Revogar o convite ${codigo}?`,
    revogarTexto: "O link deixa de funcionar na hora. Quem já entrou continua no servidor.",
    vazio: "Nenhum convite ativo. Use criar convite para gerar um link.",
    carregando: "Carregando os convites…",
    erro: "Não deu para carregar os convites.",
    criarTitulo: "Criar convite",
    destino: "Canal de destino",
    destinoAjuda: "Quem entrar pelo link chega direto neste lugar.",
    link: "Link do convite",
    gerar: "Gerar link",
    gerando: "Gerando o link…",
    copiar: "Copiar link",
    copiado: "Link copiado",
    concluir: "Concluir",
    revogado: "Convite revogado.",
    semCanais: "Crie um canal antes de convidar alguém.",
  },

  /** Cargos. */
  cargosPagina: {
    lista: "Cargos",
    contagem: (n: number) => plural(n, "cargo", "cargos"),
    criar: "Criar cargo",
    novoNome: "Novo cargo",
    todos: "@todos",
    todosAjuda: "Vale para todo mundo no servidor. Os outros cargos acrescentam o que for preciso por cima.",
    nome: "Nome do cargo",
    cor: "Cor",
    semCor: "Sem cor",
    separado: "Mostrar separado na lista de membros",
    separadoAjuda: "As pessoas deste cargo aparecem num grupo só delas, acima das outras.",
    permissoes: "Permissões",
    subir: (nome: string) => `Subir o cargo ${nome}`,
    descer: (nome: string) => `Descer o cargo ${nome}`,
    apagar: "Apagar cargo",
    apagarTitulo: (nome: string) => `Apagar o cargo ${nome}?`,
    apagarTexto: "Quem tem o cargo o perde. Não dá para desfazer.",
    naoSalvo: "Alterações não salvas",
    descartar: "Descartar",
    salvar: "Salvar",
    salvo: "Cargo salvo.",
    carregando: "Carregando os cargos…",
    escolha: "Escolha um cargo para editar.",
    pessoas: (n: number) => plural(n, "pessoa", "pessoas"),
    semPermissaoDeEditar: "Você pode ver este cargo, mas não editá-lo.",
    acimaDeVoce: "Este cargo está acima do seu e não pode ser editado.",
  },

  /** Membros e moderação. */
  membrosPagina: {
    total: (n: number) => plural(n, "pessoa", "pessoas"),
    buscar: "Buscar pessoas",
    buscarPlaceholder: "Buscar por nome",
    filtroDeCargo: "Filtrar por cargo",
    todosOsCargos: "Todos os cargos",
    pessoa: "Pessoa",
    cargos: "Cargos",
    entrouEm: "Entrou em",
    semCargo: "Sem cargo",
    vazio: "Ninguém com esse nome.",
    vazioDica: "Confira a escrita ou escolha outro cargo no filtro.",
    carregando: "Carregando as pessoas…",
    erro: "Não deu para carregar as pessoas.",
    dadosDeAntes: "Não deu para atualizar a lista agora. Mostrando os dados de antes.",
    acoes: (nome: string) => `Ações para ${nome}`,
    gerenciarCargos: "Mudar cargos",
    cargosDe: (nome: string) => `Cargos de ${nome}`,
    semCargosNoServidor: "O servidor ainda não tem cargos.",
    castigo: "Deixar de castigo",
    tirarCastigo: "Tirar o castigo",
    castigoPor: (rotulo: string) => `Em castigo por ${rotulo}`,
    umMinuto: "1 minuto",
    dezMinutos: "10 minutos",
    umaHora: "1 hora",
    umDia: "1 dia",
    umaSemana: "1 semana",
    silenciarNaVoz: "Silenciar na sala de voz",
    ensurdecerNaVoz: "Ensurdecer na sala de voz",
    moverPara: "Mover para",
    desconectarDaSala: "Desconectar da sala",
    mostrarMais: "Mostrar mais pessoas",
    expulsar: "Expulsar",
    banir: "Banir",
    expulsarTitulo: (nome: string) => `Expulsar ${nome}?`,
    expulsarTexto: "A pessoa sai do servidor e pode voltar por um novo convite.",
    banirTitulo: (nome: string) => `Banir ${nome}?`,
    banirTexto: "A pessoa sai do servidor e não consegue voltar, nem com convite.",
    motivo: "Motivo (opcional)",
    motivoAjuda: "Só quem modera o servidor vê o motivo.",
    apagarMensagens: "Apagar as mensagens das últimas 24 horas",
    apagarMensagensAjuda: "As mensagens da pessoa nesse período somem de todos os canais.",
    cancelar: "Cancelar",
    expulsou: (nome: string) => `${nome} não está mais no servidor.`,
    baniu: (nome: string) => `${nome} foi banido do servidor.`,
    castigou: (nome: string) => `${nome} está de castigo.`,
    tirouCastigo: (nome: string) => `${nome} saiu do castigo.`,
    recusou: "O servidor recusou a ação.",
    voce: "você",
    dono: "dono",
  },

  /** Banimentos. */
  banimentosPagina: {
    razao: "Motivo",
    semRazao: "Sem motivo",
    perdoar: "Perdoar",
    perdoarPessoa: (nome: string) => `Perdoar ${nome}`,
    perdoada: (nome: string) => `${nome} pode voltar ao servidor.`,
    vazio: "Ninguém está banido.",
    vazioDica: "Quando alguém for banido, aparece aqui e pode ser perdoado.",
    carregando: "Carregando os banimentos…",
    erro: "Não deu para carregar os banimentos.",
  },

  /** Quando a pessoa não pode estar numa seção. */
  semAcesso: {
    titulo: "Nada para administrar aqui",
    texto: "Você não tem permissão para mexer nas configurações deste servidor.",
  },

  /** Estados que as páginas dividem. */
  estados: {
    tentarDeNovo: "Tentar de novo",
    carregando: "Carregando…",
  },
} as const;
