import { plural } from "nucleo/lib/plural";

/** A casa: conversas diretas, grupos, notas, amigos e a chamada recebida. */
export const casa = {
  coluna: {
    rotulo: "Mensagens diretas",
    titulo: "Mensagens",
    secaoDeConversas: "Conversas",
    novoGrupo: "Novo grupo",
    amigos: "Amigos",
    amigosComPedidos: (n: number) => `Amigos, ${plural(n, "pedido pendente", "pedidos pendentes")}`,
    semConversas: {
      titulo: "Nenhuma conversa ainda",
      texto: "Abra a conversa com um amigo ou peça amizade pelo nome de usuário.",
      verAmigos: "Ver amigos",
    },
    notas: "Notas pessoais",
    grupo: (n: number) => plural(n, "pessoa", "pessoas"),
    naoLidas: (n: number) => plural(n, "não lida", "não lidas"),
    semMensagens: "Sem mensagens ainda",
    silenciada: "silenciada",
    semConexao: "Sem conexão: as conversas podem estar desatualizadas",
  },

  amigos: {
    titulo: "Amigos",
    abas: {
      rotulo: "Lista de amigos",
      online: "Online",
      todos: "Todos",
      pedidos: "Pedidos",
      pedidosComNumero: (n: number) => `Pedidos · ${String(n)}`,
      bloqueados: "Bloqueados",
    },
    secao: {
      online: (n: number) => `ONLINE — ${String(n)}`,
      todos: (n: number) => `TODOS OS AMIGOS — ${String(n)}`,
      recebidos: (n: number) => `PEDIDOS RECEBIDOS — ${String(n)}`,
      enviados: (n: number) => `PEDIDOS ENVIADOS — ${String(n)}`,
      bloqueados: (n: number) => `BLOQUEADOS — ${String(n)}`,
    },
    vazio: {
      online: "Ninguém está online agora. Quando alguém entrar, aparece aqui.",
      todos: "Você ainda não tem amigos. Peça amizade pelo nome de usuário, no campo acima.",
      pedidos: "Nenhum pedido pendente.",
      bloqueados: "Você não bloqueou ninguém.",
    },
    semConexao: "Sem conexão: a lista pode estar desatualizada.",
    adicionar: {
      rotulo: "Adicionar por nome de usuário",
      placeholder: "Nome de usuário, por exemplo @ana",
      botao: "Pedir amizade",
      enviado: (nome: string) => `Pedido enviado para @${nome}.`,
      recusado: "Não deu para enviar o pedido. Confira o nome e veja se vocês já não são amigos.",
      semConexao: "Sem conexão. Tente de novo quando voltar.",
    },
    acoes: {
      mensagem: "Mensagem",
      mensagemPara: (nome: string) => `Mensagem para ${nome}`,
      maisAcoes: (nome: string) => `Mais ações para ${nome}`,
      bloquear: "Bloquear",
      removerAmizade: "Remover amizade",
      aceitar: "Aceitar",
      aceitarDe: (nome: string) => `Aceitar pedido de ${nome}`,
      recusar: "Recusar",
      recusarDe: (nome: string) => `Recusar pedido de ${nome}`,
      cancelar: "Cancelar pedido",
      cancelarPara: (nome: string) => `Cancelar pedido para ${nome}`,
      desbloquear: "Desbloquear",
      desbloquearA: (nome: string) => `Desbloquear ${nome}`,
    },
    status: {
      online: "Online",
      idle: "Ausente",
      dnd: "Não perturbe",
      offline: "Offline",
    },
    pedidoRecebido: "Quer ser sua amiga ou seu amigo",
    pedidoEnviado: "Aguardando resposta",
  },

  grupo: {
    titulo: "Novo grupo",
    descricao: "Escolha um nome e as pessoas que entram. Dá para mudar depois.",
    rotuloDoNome: "Nome do grupo",
    nomeObrigatorio: "Dê um nome ao grupo.",
    pessoas: "Pessoas",
    semAmigos: "Você ainda não tem amigos para convidar. Peça amizade primeiro.",
    escolhaAlguem: "Escolha pelo menos uma pessoa.",
    criar: "Criar grupo",
    falhou: "Não deu para criar o grupo. Tente de novo.",
    gerenciar: "Gerenciar grupo",
    gerenciarDescricao: "Nome, pessoas e saída do grupo.",
    salvarNome: "Salvar nome",
    adicionar: "Adicionar ao grupo",
    adicionarNenhum: "Todos os seus amigos já estão no grupo.",
    remover: (nome: string) => `Remover ${nome}`,
    transferir: (nome: string) => `Passar o grupo para ${nome}`,
    acaoRemover: "Remover",
    acaoTransferir: "Passar o grupo",
    sair: "Sair do grupo",
    donoDoGrupo: "dono",
    voce: "você",
    pessoasDoGrupo: "Pessoas do grupo",
  },

  conversa: {
    ligar: "Ligar",
    ligarPara: (nome: string) => `Ligar para ${nome}`,
    ligarNoGrupo: (nome: string) => `Ligar no grupo ${nome}`,
    video: "Vídeo",
    videoCom: (nome: string) => `Chamada de vídeo com ${nome}`,
    silenciar: "Silenciar avisos desta conversa",
    semConexaoParaLigar: "Sem conexão para ligar agora.",
    indisponivel: "Esta conversa não está mais disponível.",
    voltarAosAmigos: "Voltar aos amigos",
    bloqueada: (nome: string) => `Você bloqueou ${nome}. Desbloqueie para voltar a conversar.`,
    bloqueadoPor: (nome: string) => `Você não pode enviar mensagens para ${nome}.`,
    desbloquear: "Desbloquear",
    notasTitulo: "Notas pessoais",
    notasTexto: "Só você vê estas mensagens.",
    perfil: (nome: string) => `Perfil de ${nome}`,
    sobre: "Sobre",
    emComum: "Servidores em comum",
    emComumNenhum: "Vocês não têm servidores em comum.",
    emComumCarregando: "Procurando servidores em comum",
    emComumFalhou: "Não deu para ver os servidores em comum.",
    bloquear: "Bloquear",
    denunciar: "Denunciar",
    denunciarTitulo: (nome: string) => `Denunciar ${nome}?`,
    denunciarTexto: "A equipe do servidor revisa a denúncia. A pessoa não é avisada.",
    denunciarConfirmar: "Denunciar",
    denunciada: "Denúncia enviada.",
  },

  chamada: {
    rotulo: (nome: string) => `${nome} está te ligando`,
    noGrupo: (nome: string) => `Em ${nome}`,
    subtitulo: "Chamada de voz e vídeo",
    atender: "Atender",
    atenderDe: (nome: string) => `Atender chamada de ${nome}`,
    recusar: "Recusar",
    recusarDe: (nome: string) => `Recusar chamada de ${nome}`,
    soAudio: "Atender só com áudio",
    sinalTeclaAtender: "Ctrl+Enter",
    sinalTeclaRecusar: "Esc",
  },

  avisos: {
    titulo: "Avisos no computador",
    texto: "Quer ser avisado de mensagens diretas, menções e chamadas com o app em segundo plano?",
    ativar: "Ativar avisos",
    agoraNao: "Agora não",
    negado: "Os avisos estão bloqueados neste navegador. Libere nas permissões do site para recebê-los.",
    concedido: "Avisos ativados.",
  },
} as const;
