import { plural } from "nucleo/lib/plural";

/**
 * Textos das configurações essenciais (PRD 4.6): perfil, conta, dispositivos,
 * voz e vídeo, notificações e aparência. Sem texto de engenharia: quem erra a
 * senha lê "senha incorreta", não o nome do erro do servidor.
 */
export const config = {
  titulo: "Configurações",
  navegacao: "Seções das configurações",
  grupoConta: "Minha conta",
  grupoApp: "App",
  perfil: "Perfil",
  conta: "Conta",
  dispositivos: "Dispositivos",
  vozEVideo: "Voz e vídeo",
  notificacoes: "Notificações",
  aparencia: "Aparência",
  sair: "Sair",
  fechar: "Fechar as configurações",
  dicaDeEsc: "Esc",
  abrir: "Configurações",
  salvouComSucesso: "Alterações salvas.",
  descartarAlteracoes: "Descartar",
  salvar: "Salvar",
  salvando: "Salvando…",
  carregando: "Carregando…",
  naoDeuParaCarregar: "Não deu para carregar estes dados. Tente de novo.",

  subtitulos: {
    perfil: "Como o grupo vê você no Vortex.",
    conta: "Seus dados de acesso.",
    dispositivos: "Onde a sua conta está conectada agora.",
    vozEVideo: "Como você soa e aparece nas salas.",
    notificacoes: "O que merece interromper você.",
    aparencia: "Como o Vortex se parece para você.",
  },

  barraDeSalvar: {
    recado: "Você tem alterações não salvas",
  },

  perfilTela: {
    banner: "Banner do perfil",
    trocarBanner: "Trocar banner",
    removerBanner: "Remover banner",
    avatar: "Foto do perfil",
    trocarAvatar: "Trocar foto",
    removerAvatar: "Remover foto",
    enviando: "Enviando…",
    nomeDeExibicao: "Nome de exibição",
    nomeDeExibicaoDica: "É o nome que o grupo vê nas mensagens e nas salas.",
    sobreVoce: "Sobre você",
    sobreVocePlaceholder: "Conte em poucas palavras quem você é",
    recado: "Recado",
    recadoPlaceholder: "O que você está fazendo agora?",
    presenca: "Presença",
    previa: "Prévia do seu cartão",
    previaLegenda: "Assim o grupo vê você ao clicar no seu nome.",
    sobre: "Sobre",
    semMidia: "Este servidor não guarda imagens, então a foto e o banner não podem ser trocados.",
    imagemInvalida: "Escolha uma imagem PNG, JPG ou GIF.",
    falhouImagem: "Não deu para enviar a imagem. Tente outra.",
    contador: (usados: number, maximo = 0) => `${usados} de ${maximo}`,
    presencas: {
      online: "Online",
      idle: "Ausente",
      dnd: "Não perturbe",
      invisivel: "Invisível",
    },
    ajudaDaPresenca: {
      online: "Todo mundo vê que você está disponível.",
      idle: "Aparece como ausente, sem avisar que você saiu.",
      dnd: "Aparece como ocupado e silencia os avisos sonoros.",
      invisivel: "Você aparece offline para os outros, mas continua usando o app.",
    },
  },

  contaTela: {
    nomeDeUsuario: "Nome de usuário",
    nomeDeUsuarioDica: "É como as pessoas encontram você. Trocar pede a senha.",
    email: "E-mail",
    emailNovo: "Novo e-mail",
    emailDica: "O endereço novo recebe um link de confirmação antes de valer.",
    emailMostrar: "Mostrar o e-mail",
    emailEsconder: "Esconder o e-mail",
    emailIndisponivel: "Não deu para consultar o e-mail agora.",
    senha: "Senha",
    senhaMascara: "••••••••••",
    senhaAtual: "Senha atual",
    senhaNova: "Nova senha",
    senhaConfirmar: "Confirmar nova senha",
    trocarNome: "Trocar nome",
    trocarEmail: "Trocar e-mail",
    trocarSenha: "Trocar senha",
    sairDaConta: "Sair da conta",
    sairDaContaDica: "Você continua com suas conversas ao entrar de novo.",
    excluir: "Excluir conta",
    excluirDica:
      "Sua conta, seu perfil e suas mensagens diretas somem para sempre. Seus servidores continuam existindo, mas sem você. Não dá para desfazer.",
    excluirBotao: "Excluir minha conta",
    erroSenhaAtual: "A senha atual está incorreta.",
    erroEmailEmUso: "Esse e-mail já está em uso.",
    erroNomeEmUso: "Esse nome de usuário já está em uso.",
    erroSenhaFraca: "Essa senha não é aceita. Use pelo menos 8 caracteres e algo que não tenha vazado.",
    erroSenhasDiferentes: "As senhas não são iguais.",
    erroSenhaCurta: "Use pelo menos 8 caracteres.",
    erroLimite: "Tentativas demais. Espere um pouco e tente de novo.",
    erroGenerico: "Não deu para concluir agora. Tente de novo em instantes.",
    emailTrocado: "Enviamos um link de confirmação para o endereço novo.",
    senhaTrocada: "Senha alterada.",
    nomeTrocado: "Nome de usuário alterado.",
    trocarSenhaTitulo: "Trocar senha",
    trocarSenhaDescricao: "Use uma senha que você não usa em outros lugares.",
    excluirTitulo: "Excluir a conta?",
    excluirAviso: "Isso apaga sua conta para sempre. Para confirmar, digite seu nome de usuário e a senha.",
    excluirConfirmarNome: "Nome de usuário para confirmar",
    excluirConfirmar: "Excluir para sempre",
    excluirEnviado: "Enviamos um e-mail para confirmar a exclusão. A conta só some depois do clique no link.",
    excluirDono: (n: number) =>
      n === 1
        ? "Você é dono de 1 servidor. Transfira ou apague o servidor antes de excluir a conta."
        : `Você é dono de ${n} servidores. Transfira ou apague esses servidores antes de excluir a conta.`,
    cancelar: "Cancelar",
    entendi: "Entendi",
  },

  dispositivosTela: {
    esteDispositivo: "Este dispositivo",
    outros: "Outros dispositivos",
    ativoAgora: "Ativo agora",
    desde: (quando: string) => `Conectado desde ${quando}`,
    desconectar: "Desconectar",
    desconectarTodos: "Desconectar todos os outros",
    desconectarOutros: (n: number) => `Desconectar ${plural(n, "outro", "outros")}`,
    renomear: "Renomear",
    renomearRotulo: (nome: string) => `Renomear ${nome}`,
    nomeDoDispositivo: "Nome do dispositivo",
    salvarNome: "Salvar nome",
    desconectarRotulo: (nome: string) => `Desconectar ${nome}`,
    carregando: "Carregando os dispositivos…",
    vazioTitulo: "Só este dispositivo está conectado",
    vazioTexto:
      "Quando você entrar em outro computador ou navegador, ele aparece aqui para você poder desconectar.",
    semNome: "Dispositivo sem nome",
    confirmeTitulo: "Confirme com a sua senha",
    confirmeTextoUm: "Vamos desconectar este dispositivo.",
    confirmeTextoTodos: "Vamos desconectar todos os outros dispositivos.",
    confirmeSoUmaVez:
      "Pedimos a senha só desta vez: depois dela, você pode desconectar outros dispositivos sem digitar de novo.",
    senhaAtual: "Senha atual",
    senhaErro: "A senha atual está incorreta.",
    senhaVazia: "Digite a sua senha atual para continuar.",
    falhou: "Não deu para concluir agora. Tente de novo em instantes.",
    desconectado: "Dispositivo desconectado.",
    todosDesconectados: "Os outros dispositivos foram desconectados.",
    cancelar: "Cancelar",
  },

  vozTela: {
    audio: "Áudio",
    microfone: "Microfone",
    saida: "Saída",
    padraoDoSistema: "Padrão do sistema",
    semMicrofone: "Nenhum microfone encontrado. Conecte um e escolha de novo.",
    semNomes: "Dê permissão ao microfone para ver o nome dos dispositivos.",
    volumeDoMicrofone: "Volume do microfone",
    volumeDeSaida: "Volume de saída",
    testar: "Testar microfone",
    testarBotao: "Testar",
    pararTeste: "Parar o teste",
    testeTexto: "Fale algo: a barra mostra o quanto o microfone está pegando.",
    testeMedindo: "Medindo o seu microfone…",
    testeParado: "O teste está parado.",
    nivel: "Nível do microfone",
    limiarDica: "A linha marca o limiar: o microfone abre quando a sua voz passa dela.",
    erroPermissao: "Permissão negada. Libere o microfone nas permissões do navegador.",
    erroSemDispositivo: "Nenhum microfone encontrado.",
    erroEmUso: "O microfone está em uso por outro programa.",
    erroSumiu: "O microfone escolhido não está mais disponível.",
    erroGenerico: "Não foi possível abrir o microfone.",
    ruido: "Supressão de ruído",
    ruidoNiveis: {
      desligada: "Desligada",
      padrao: "Padrão",
      agressiva: "Agressiva",
    },
    ruidoAjuda: {
      desligada: "O microfone envia o som como ele chega, ruído de fundo incluído.",
      padrao: "Tira ruídos constantes, como ventoinha e ar-condicionado.",
      agressiva: "Corta também teclado e vozes ao fundo. Pode comer o fim das palavras.",
    },
    modoDeEntrada: "Modo de entrada",
    deteccao: "Detecção de voz",
    deteccaoDica: "O microfone abre sozinho quando você fala.",
    pressionar: "Pressionar para falar",
    pressionarDica: "O microfone só abre enquanto você segura uma tecla.",
    limiar: "Limiar de detecção",
    limiarAutomatico: "Ajustar o limiar sozinho",
    tecla: "Tecla",
    teclaNaoDefinida: "Nenhuma tecla",
    mudarTecla: "Mudar tecla",
    gravandoTecla: "Aperte a nova tecla…",
    cancelarGravacao: "Cancelar",
    teclaEmConflito: "Essa combinação já é usada por outra ação de voz, então nenhuma das duas funciona.",
    teclaSegurando: "Segurando a tecla: o microfone está aberto.",
    atrasoAoSoltar: "Atraso ao soltar",
    camera: "Câmera",
    cameraDesligada: "Câmera desligada",
    cameraPrevia: "Só você vê esta prévia",
    cameraNome: "Câmera",
    ligarPrevia: "Ligar prévia",
    desligarPrevia: "Desligar prévia",
    erroDaCamera: {
      permissao: "Permissão negada. Libere a câmera nas permissões do navegador.",
      semDispositivo: "Nenhuma câmera encontrada.",
      emUso: "A câmera está em uso por outro programa.",
      sumiu: "A câmera escolhida não está mais disponível.",
      generico: "Não foi possível abrir a câmera.",
    },
    semCamera: "Nenhuma câmera encontrada.",
    fundo: "Fundo do vídeo",
    fundos: {
      nenhum: "Nenhum",
      desfoque: "Desfocar",
      imagem: "Imagem",
    },
    fundoDica: "O fundo vale quando a câmera estiver ligada numa sala.",
    espelhar: "Espelhar a minha imagem",
    espelharDica: "Só você vê espelhado. Os outros veem normal.",
  },

  notificacoesTela: {
    avisarQuando: "Avisar quando…",
    colunaNotificacao: "Notificação",
    colunaSom: "Som",
    notificacaoDe: (evento: string) => `Notificação: ${evento}`,
    somDe: (evento: string) => `Som: ${evento}`,
    sonsDeVoz: "Sons de entrada e saída das salas",
    sonsDeVozDica: "Um aviso curto quando alguém entra, sai ou você muda o microfone.",
    silenciados: "Silenciados",
    silenciadosVazio: "Nada silenciado. Tudo chega até você.",
    silenciadoAte: (quando: string) => `Silenciado até ${quando}`,
    silenciadoPraSempre: "Silenciado até você reativar",
    reativar: "Reativar",
    reativarRotulo: (nome: string) => `Reativar ${nome}`,
  },

  aparenciaTela: {
    tema: "Tema",
    temaDica: "Passe o mouse para espiar na prévia; clique para usar.",
    temas: {
      vidro: "Vidro",
      grafite: "Grafite",
      oceano: "Oceano",
      ametista: "Ametista",
      floresta: "Floresta",
      brasa: "Brasa",
      aurora: "Aurora",
    },
    emUso: "Em uso",
    personalizado: "Personalizado",
    personalizar: "Personalizar",
    personalizarDica: "Parte do tema escolhido. Mexer aqui marca o tema como personalizado.",
    voltarAoTema: "Voltar ao tema",
    matiz: "Matiz",
    intensidade: "Intensidade",
    corDeDestaque: "Cor de destaque",
    destaques: {
      lavanda: "Lavanda",
      menta: "Menta",
      ceu: "Céu",
      rosa: "Rosa",
      pessego: "Pêssego",
      limao: "Limão",
    },
    outraCor: "Outra cor",
    seletorDeCor: "Escolher a cor de destaque",
    campoHex: "Código da cor (hexadecimal)",
    hexInvalido: "Use três ou seis dígitos, como #35c2cc.",
    destaqueAjustado: "Ajustamos o tom para manter a leitura",
    antes: "Antes",
    depois: "Depois",
    semPaleta: "Essa combinação não ficaria legível, então o tema de fábrica continua valendo.",
    ajusteAutomatico: "As cores se ajustam sozinhas para continuarem legíveis.",
    soEscuro: "Por enquanto só existe o tema escuro.",
    previa: "Prévia",
    previaDe: (nome: string) => `Prévia do tema ${nome}`,
    previaPersonalizada: "Sua personalização",
    previaCanais: "Canais",
    previaCanalAtivo: "geral",
    previaCanalOutro: "jogos",
    previaNomeA: "Ana",
    previaNomeB: "Beto",
    previaMensagemA: "Bora jogar hoje à noite, ",
    previaMencao: "@você",
    previaMensagemB: "Chego em dez minutos.",
    previaBotao: "Entrar na sala",
    previaFalando: "Ana falando",
    valorGraus: (n: number) => `${n}°`,
    valorPorcento: (n: number) => `${n}%`,
    vidroETitulo: "Vidro e fundo",
    vidroEDica: "Ajusta o quanto os painéis deixam o fundo aparecer. Sólido também deixa o app mais leve em computador fraco.",
    vidro: "Vidro",
    vidroTranslucido: "Translúcido",
    vidroSolido: "Sólido",
    vidroValor: (n: number) => (n === 0 ? "Sólido" : n === 100 ? "Translúcido" : `${n}%`),
    brilho: "Brilho de fundo",
    brilhoDica: "As manchas de cor atrás do app. As cores acompanham o tema escolhido.",
    brilhoValor: (n: number) => (n === 0 ? "Desligado" : `${n}%`),
    leituraTitulo: "Mensagens e texto",
    mensagens: "Mensagens",
    confortavel: "Confortável",
    confortavelDica: "Foto de cada pessoa e mais espaço entre as mensagens.",
    compacta: "Compacta",
    compactaDica: "Sem foto, com a hora ao lado e as mensagens mais juntas.",
    tamanhoDoTexto: "Tamanho do texto",
    tamanhoDoTextoValor: (n: number) => `${n}%`,
    movimentoTitulo: "Movimento",
    reduzirAnimacoes: "Reduzir animações",
    reduzirAnimacoesDica: "Desliga transições e animações que não são essenciais.",
    seguirOSistema: "Seguir o que o sistema pede",
    restaurarAjustes: "Restaurar vidro, fundo e texto",
  },
} as const;
