import { plural } from "nucleo/lib/plural";

export const salas = {
  titulo: "Salas",
  entrarNaSala: "Entrar na sala",
  sairDaSala: "Sair da sala",
  vazia: "Ninguém está na sala agora.",
  participantes: (n: number) => plural(n, "participante", "participantes"),
  naSala: (n: number) => plural(n, "pessoa na sala", "pessoas na sala"),
  criarSala: "Criar sala",
  /** Nome de quem ainda não chegou ao servidor (membro não carregado). */
  alguem: "Alguém",
  casa: "Início",
  secaoDeSalas: "Salas de voz",
  secaoDeTexto: "Canais de texto",
  semCanaisDeTexto: "Nenhum canal de texto.",
  carregandoServidor: "Carregando o servidor",
  presencaDesatualizada: "Presença desatualizada",
  conectando: "Entrando na sala…",
  vocePodeEntrar: "Você não pode entrar nesta sala.",
  semConexaoParaEntrar: "Sem conexão: não dá para entrar na sala agora.",
  servidorVazio: {
    titulo: "Ainda não há salas",
    comPermissao: "Crie uma sala de voz para o grupo se encontrar e compartilhar a tela.",
    semPermissao: "Ninguém criou uma sala de voz neste servidor ainda.",
    convidar: "Convidar pessoas",
  },
  criar: {
    titulo: "Criar sala",
    descricao: "Uma sala de voz onde o grupo se encontra e compartilha a tela.",
    rotuloDoNome: "Nome da sala",
    nomeObrigatorio: "Dê um nome à sala.",
    confirmar: "Criar",
    falhou: "Não deu para criar a sala. Tente de novo.",
  },
  convite: {
    titulo: "Convidar pessoas",
    descricao: "Quem receber este link entra no servidor.",
    gerando: "Gerando o link…",
    falhou: "Não deu para criar o convite.",
    copiar: "Copiar link",
    copiado: "Link copiado",
    rotuloDoLink: "Link do convite",
  },
} as const;
