export const voz = {
  microfone: "Microfone",
  ativarMicrofone: "Ativar microfone",
  silenciarMicrofone: "Silenciar microfone",
  audioRecebido: "Áudio recebido",
  ensurdecer: "Ensurdecer",
  desensurdecer: "Desfazer ensurdecimento",
  camera: "Câmera",
  ligarCamera: "Ligar câmera",
  desligarCamera: "Desligar câmera",
  compartilharTela: "Compartilhar tela",
  pararDeCompartilhar: "Parar de compartilhar",
  sairDaChamada: "Sair da chamada",
  conectando: "Conectando…",
  reconectando: "Reconectando…",
  conectado: "Conectado",
  qualidade: {
    otima: "Conexão ótima",
    boa: "Conexão boa",
    instavel: "Conexão instável",
    perdida: "Conexão perdida",
  },
  falando: (nome: string) => `${nome} está falando`,
  sinalTransmitindo: "TRANSMITINDO",
} as const;
