export const voz = {
  microfone: "Microfone",
  ativarMicrofone: "Ativar microfone",
  silenciarMicrofone: "Silenciar microfone",
  audioRecebido: "Áudio recebido",
  ensurdecer: "Ensurdecer",
  desensurdecer: "Desfazer ensurdecimento",
  camera: "Câmera",
  ligarCamera: "Ligar câmera",
  desligarCamera: "Desligar câmera",
  compartilharTela: "Compartilhar tela",
  pararDeCompartilhar: "Parar de compartilhar",
  sairDaChamada: "Sair da chamada",
  conectando: "Conectando…",
  reconectando: "Reconectando…",
  conectado: "Conectado",
  qualidade: {
    otima: "Conexão ótima",
    boa: "Conexão boa",
    instavel: "Conexão instável",
    perdida: "Conexão perdida",
  },
  falando: (nome: string) => `${nome} está falando`,
  sinalTransmitindo: "TRANSMITINDO",
  ninguemFalando: "Ninguém está falando",
  sala: "Sala de voz",
  chamada: "Chamada em andamento",
  controles: "Controles de voz",
  pessoasNaChamada: "Pessoas na chamada",
  qualidadeDaTransmissao: "Qualidade da transmissão",
  verPalco: "Ver palco",
  voltarAoPalco: "Voltar ao palco",
  estado: {
    falando: "Falando",
    transmitindo: "Transmitindo tela",
    mudo: "Sem áudio",
  },
  fixarNoCanto: {
    tl: "Fixar no canto superior esquerdo",
    tr: "Fixar no canto superior direito",
    bl: "Fixar no canto inferior esquerdo",
    br: "Fixar no canto inferior direito",
  },
} as const;
