import { plural } from "nucleo/lib/plural";

export const voz = {
  microfone: "Microfone",
  ativarMicrofone: "Ativar microfone",
  silenciarMicrofone: "Silenciar microfone",
  audioRecebido: "Áudio recebido",
  ensurdecer: "Ensurdecer",
  desensurdecer: "Desfazer ensurdecimento",
  camera: "Câmera",
  ligarCamera: "Ligar câmera",
  desligarCamera: "Desligar câmera",
  compartilharTela: "Compartilhar tela",
  pararDeCompartilhar: "Parar de compartilhar",
  sairDaChamada: "Sair da chamada",
  conectando: "Conectando…",
  reconectando: "Reconectando…",
  conectado: "Conectado",
  qualidade: {
    otima: "Conexão ótima",
    boa: "Conexão boa",
    instavel: "Conexão instável",
    perdida: "Conexão perdida",
  },
  estaFalando: "está falando",
  falando: (nome: string) => `${nome} está falando`,
  sinalTransmitindo: "TRANSMITINDO",
  ninguemFalando: "Ninguém está falando",
  sala: "Sala de voz",
  chamada: "Chamada em andamento",
  controles: "Controles de voz",
  painelDaChamada: "Controles da chamada",
  pessoasNaChamada: "Pessoas na chamada",
  qualidadeDaTransmissao: "Qualidade da transmissão",
  verPalco: "Ver palco",
  voltarAoPalco: "Voltar ao palco",
  estado: {
    falando: "Falando",
    transmitindo: "Transmitindo tela",
    mudo: "Sem áudio",
    surdo: "Sem ouvir",
  },
  palco: {
    rotulo: (sala: string) => `Palco da sala ${sala}`,
    pessoas: (n: number) => plural(n, "pessoa", "pessoas"),
    aoVivo: (nome: string) => `${nome} ao vivo`,
    emTransmissao: (nome: string) => `${nome} transmitindo`,
    suaTela: "Sua tela",
    vocePassaTransmitindo: "Você está transmitindo",
    recolherFaixa: "Recolher miniaturas",
    expandirFaixa: "Mostrar miniaturas",
    telaDe: (nome: string) => `Tela de ${nome}`,
    voce: "Você",
    abrirChat: "Abrir o chat",
    verEmGrade: "Ver em grade",
    verEmFoco: "Ver em foco",
    assistir: (nome: string) => `Assistir à tela de ${nome}`,
    pararDeAssistir: "Parar de assistir",
    recebendoQuadro: "Recebendo o primeiro quadro…",
    ninguemTransmitindo: "Ninguém está transmitindo.",
    pessoaNaSala: "Na sala",
    mudoDe: (nome: string) => `${nome} está sem áudio`,
    grade: "Pessoas na sala",
  },
  conexao: {
    conectandoASala: "Conectando à sala…",
    reconectando: "Reconectando…",
    reconectandoDetalhe: "Sua conexão oscilou. Não precisa fazer nada.",
    falhouTitulo: (sala: string) => `Não deu para entrar na ${sala}`,
    falhouGenerico: "O servidor de voz não respondeu.",
    tentarDeNovo: "Tentar de novo",
    voltar: "Voltar",
    foraTitulo: (sala: string) => `Você não está na ${sala}`,
    foraTexto: "Quando quiser, é só entrar de novo. A sala continua aberta.",
    entrarNaSala: "Entrar na sala",
    saiu: (sala: string) => `Você saiu da ${sala}`,
  },
  transmitir: {
    titulo: "O que você quer mostrar?",
    abas: "Tipo de fonte",
    telas: "Telas",
    janelas: "Janelas",
    fontes: "Fonte a transmitir",
    escolhida: ", escolhida",
    semFontes: "Nada para mostrar aqui.",
    carregandoFontes: "Procurando telas e janelas…",
    falhaAoListar:
      "Não deu para listar as telas. Você ainda pode escolher no seletor do sistema.",
    seletorDoSistema:
      "O seletor do sistema abre depois de você escolher transmitir.",
    som: "Transmitir o som",
    somDescricao: "Quem assiste ouve o áudio do que você está mostrando.",
    faixas: "Faixas de áudio",
    faixasDescricao: "Desmarque o que não deve ir na transmissão.",
    somIndisponivel: "Este navegador não transmite o som da tela.",
    resolucao: "Resolução",
    quadros: "Quadros por segundo",
    notaDeRede:
      "1440p a 60 quadros usa bastante internet. Se a transmissão travar, baixe a resolução ou os quadros.",
    cancelar: "Cancelar",
    transmitir: "Transmitir",
    iniciando: "Iniciando…",
    semCaptura: "Este navegador não consegue compartilhar a tela.",
    semPermissao:
      "Você não tem permissão para transmitir nesta sala. Peça a quem cuida do servidor.",
  },
  pip: {
    arrastar: "Mover a chamada para outro canto",
    semVideo: "Sem vídeo agora",
    videoDe: (nome: string) => `Vídeo de ${nome}`,
  },
  destacar: {
    destacar: "Destacar chamada",
    trazerDeVolta: "Trazer a chamada de volta",
    janela: "Chamada destacada",
    salaRotulo: (sala: string) => `Sala ${sala}, quem está na sala`,
    abrirVortex: "Abrir Vortex",
    controles: "Controles da sala",
    transmissao: (nome: string) => `Transmissão de ${nome}`,
    ninguem: "Ninguém por aqui",
  },
  fixarNoCanto: {
    tl: "Fixar no canto superior esquerdo",
    tr: "Fixar no canto superior direito",
    bl: "Fixar no canto inferior esquerdo",
    br: "Fixar no canto inferior direito",
  },
} as const;
